.header on
.mode column

CREATE TABLE COURSES (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	CourseNum TEXT NOT NULL, 
	CourseName TEXT NOT NULL
);

CREATE TABLE REQUIREMENTS (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	CourseID INTEGER NOT NULL, 
	RequirementID INTEGER NOT NULL,
	FOREIGN KEY(CourseID) REFERENCES COURSES(ID), 
	FOREIGN KEY(RequirementID) REFERENCES COURSES(ID)
);


INSERT INTO COURSES(CourseNum, CourseName) VALUES ("CS173", "Intro to Computer Science");
INSERT INTO COURSES(CourseNum, CourseName) VALUES ("CS174", "Object Oriented Programming");
INSERT INTO COURSES(CourseNum, CourseName) VALUES ("CS274", "Computer Architecture");
INSERT INTO COURSES(CourseNum, CourseName) VALUES ("CS275", "Software Engineering");
INSERT INTO COURSES(CourseNum, CourseName) VALUES ("CS377", "Database Design");

INSERT INTO REQUIREMENTS(CourseID, RequirementID) VALUES (2,1);
INSERT INTO REQUIREMENTS(CourseID, RequirementID) VALUES (3,2);
INSERT INTO REQUIREMENTS(CourseID, RequirementID) VALUES (4,2);
INSERT INTO REQUIREMENTS(CourseID, RequirementID) VALUES (5,4);

SELECT * FROM COURSES;
SELECT * FROM REQUIREMENTS;
